version: '3.4'

services:

  minio-gateway:
    image: minio
    restart: on-failure
    build: .
    environment:
      MINIO_ACCESS_KEY: "12345678"
      MINIO_SECRET_KEY: "12345678"
      INSTANCE_TYPE: gateway_s3
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    ports:
      - "8080:8080"
