version: '3.4'

services:

  minio-http:
    image: docker.pkg.github.com/cloudwebmanage/cwm-worker-deployment-minio/minio
    build: .
    ports:
      - "8080:8080"
    environment:
      MINIO_REGION_NAME: "EU"
      MINIO_DOMAIN: "example007.com"
      MINIO_ACCESS_KEY: "12345678"
      MINIO_SECRET_KEY: "12345678"
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/cache"
      MINIO_CACHE_EXCLUDE: "*.pdf"
      MINIO_CACHE_QUOTA: "80"
      MINIO_CACHE_AFTER: "3"
      MINIO_CACHE_WATERMARK_LOW: "70"
      MINIO_CACHE_WATERMARK_HIGH: "90"
      MINIO_AUDIT_WEBHOOK_ENABLE_target1: "on"
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1: ""
      MINIO_AUDIT_WEBHOOK_ENDPOINT_target1: http://logger:8500
      MINIO_GATEWAY_DEPLOYMENT_ID: "docker-compose-http"
    volumes:
      - "storage:/storage"
      - "cache:/cache"

  minio-https:
    image: docker.pkg.github.com/cloudwebmanage/cwm-worker-deployment-minio/minio
    build: .
    ports:
      - "8443:8443"
    environment:
      MINIO_REGION_NAME: "EU"
      MINIO_DOMAIN: "example007.com"
      MINIO_ACCESS_KEY: "12345678"
      MINIO_SECRET_KEY: "12345678"
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/cache"
      MINIO_CACHE_EXCLUDE: "*.pdf"
      MINIO_CACHE_QUOTA: "80"
      MINIO_CACHE_AFTER: "3"
      MINIO_CACHE_WATERMARK_LOW: "70"
      MINIO_CACHE_WATERMARK_HIGH: "90"
      CERTIFICATE_PEM: "-----BEGIN CERTIFICATE-----\nMIIDCTCCAfGgAwIBAgIUebacs5jlDI2Wy4EXGcvXu6x7e9AwDQYJKoZIhvcNAQEL\nBQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIwMDEyMTEwMTU0OFoXDTIyMTEx\nMDEwMTU0OFowFDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEF\nAAOCAQ8AMIIBCgKCAQEA0CMe/fuMrIRwalCnVGeZVAY/LEItoKD1FJcG2UGd3AUO\nDGlxFtd5xBTyfc3+tvscZSbqOOrT2XuEUeGzmIiuDx9k9k28KeMxRYf5tB5rdKm8\nFokuuczXqowDfanDmbu4QhTrHM1IX2FFSoRlQq4e/N1TP9Nm5eUqSH44ONavCJM5\n857QoScv82ot7oaZ6Sqaweau5wrxTTBAyTRrQ+OKMyMgUs8fpRON+oBbgEpDAeXk\nNxe9ck8IBqrnH8tQJbv1dfDr5a9Boa0DCrjHO/VHDVh/GzU7FoQW9B640EOJXCSj\n3xZpJAwgNXrF8gX7kBGQWjFNqltubbRFxUAQS3ULyQIDAQABo1MwUTAdBgNVHQ4E\nFgQUFf9QJ016QGvtEKN83Em8scdS/1owHwYDVR0jBBgwFoAUFf9QJ016QGvtEKN8\n3Em8scdS/1owDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEATd1z\nKkMxN58FbNkS4aHPVaKxb4fhIer5yhBRpdBHXl6AWyDaTLr0uAVH9CSyYAzETGGV\nAX4CdwCkHRq1DuXcn8vWzt2BBY6E4x9x/7TyeXtzj38R5nW9OOf5UTtK4e/3M/KA\ngAUEyBeTPwPnCxEPTvd1WFktQyHgCth6msPdAjFRf75u2vT5zAnQbREjsRnp6kpZ\nYXxAJDCwhAKrAoPeBRc5XAqPGB9oYp/8filHTj8CpErid6JWpSvFw+6JrEDg/pVe\nf/G7niVrMtyeermVLca3WeZPQ5NReMXmJ3pOg2MXDKcy4E4pvkM6oQmYbtKsPAvx\n64hRJtzD6RCaFmQ1FQ==\n-----END CERTIFICATE-----"
      CERTIFICATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQIx79+4yshHBq\nUKdUZ5lUBj8sQi2goPUUlwbZQZ3cBQ4MaXEW13nEFPJ9zf62+xxlJuo46tPZe4RR\n4bOYiK4PH2T2Tbwp4zFFh/m0Hmt0qbwWiS65zNeqjAN9qcOZu7hCFOsczUhfYUVK\nhGVCrh783VM/02bl5SpIfjg41q8IkznzntChJy/zai3uhpnpKprB5q7nCvFNMEDJ\nNGtD44ozIyBSzx+lE436gFuASkMB5eQ3F71yTwgGqucfy1Alu/V18Ovlr0GhrQMK\nuMc79UcNWH8bNTsWhBb0HrjQQ4lcJKPfFmkkDCA1esXyBfuQEZBaMU2qW25ttEXF\nQBBLdQvJAgMBAAECggEAJXZs2aIxS8v6v+gMdjC/dFQ7gqfWtpbCBha48NnSpAt0\n398Kr+XQ0O5ER0iQlDbWgY5jkiMSRo7o3iQVw1q2mZo4/ew39gIimDVFSJpBFRqH\n9DZ05pRsLRJOfovT3RPgsmQ5fVGluSU055i08S+N/E2J8m8GklKRLcMqM3DQyGYE\nFK792nVarXJqo16tlkeO1ZChNy4oRLrdvpRK5FDsnX9Tuy/DTYFL+0u3ck+4XtgH\nZuEaOUwEmS8W8lQgE4B7Q8Zv0gdtLTw9XQuUmyFCEy3+dODG1IhzKqx1ldVEA2Yc\nKXlGO3rPbbdicDkqU1RIV0kI+d9+OzznhnCtv2zRQQKBgQD8rg9dD2OK+ZkW81Yp\nyLfWa6Vl8dfiCLkb8uumecr9OrBMLqEgfJMIZnOtzE9zxq5vSTHEYbtbMlqTd67I\n0ovVSIWdl9AEl2iNTk8Ha09fGjnlMjsFUe+80U0gHCwLytIaVeAsSZ3j0XJVNNE0\nvLh/TfY1AgITvDTGuWrOBtHXLQKBgQDS3zuJ70ZasXslnPkIdLcPv+nO0lDY3L9Q\nuyfWDR3TaCxQIw/oIFQ3hiqnq1EgV5gzPQ6plRXvNlP4TYC9rO+9eExpHjrtExdZ\nfsIVyLU+v9BZyFqTDyoEeXZawkQ+cWrac3p53RlcPP6gqo0BlagoJfu4Ur6+uZcM\nYrl50tyojQKBgERU4ey9q6K6qw7M0YFNOYHv7HOsOkBzMXQAdn+3shBXHbQMbCB3\n7982rZPTi6z4jtWjiqTb9SnNbTcyB39hiNUt3oxmsKd9NpX4FmEgQP+r/PohYlqm\n9NkwFNZZKAQsXjMnBA+V/O/OBUhLl0PWwWIT+EAPgfZKUE9pdxuuNnMlAoGBAJHA\nPjTer7AsEEQ1NWQE2CsIqSCM+diK66lvUt9+fWkMDeTt9yaogc1G7OCrZw2Fvetc\nfm/0Xg7TbEKpvxxbFfHN3nKhtHT8xxzSom/QJIZUqjwEYaZXyuEA2y9sKyNF3WdU\nfgkRK2A3wH9oosG/oVTuvAfxGWpWePLUogJ0HpRZAoGAXDdcofIrP/IW4xjCbwBk\nqJJr4WDAeSvqscXRZb6DEsWwmvzMMI5RYwAkwOPm5MMJpXTjfUtS3Y3LjYWczlww\nN+vbIMyCeQDsgnJKJyQU6mhqw9RUUD4cmD9BgTJDlgLcVMUu3eLLrAOdjSOUfxCx\nhlQZj4ZBcZWwbF1E1VmH84g=\n-----END PRIVATE KEY-----"
      MINIO_AUDIT_WEBHOOK_ENABLE_target1: "on"
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1: ""
      MINIO_AUDIT_WEBHOOK_ENDPOINT_target1: http://logger:8500
      MINIO_GATEWAY_DEPLOYMENT_ID: "docker-compose-https"
    volumes:
      - "storage:/storage"
      - "cache:/cache"

  logger:
    image: docker.pkg.github.com/cloudwebmanage/cwm-worker-deployment-minio/last_action_logger
    build: last_action_logger
    environment:
      REDIS_HOST: redis

  redis:
    image: redis

volumes:
  storage:
  cache:
