version: '3.4'

services:

  nginx:
    image: nginx
    restart: on-failure
    build: nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      HOSTNAMES_DIR: "/hostnames"
      CDN_CACHE_ENABLE: "${CDN_CACHE_ENABLE}"
      CDN_CACHE_NOCACHE_REGEX: '\.(pdf|txt|json)$$'
    volumes:
      - "./tests/hostnames:/hostnames"
    depends_on:
      - minio

  minio:
    image: minio
    restart: on-failure
    build: .
    environment:
      MINIO_DOMAIN: "example001.com"
      MINIO_ROOT_USER: "12345678"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/cache"
      MINIO_CACHE_EXCLUDE: "*.pdf"
      MINIO_CACHE_QUOTA: "80"
      MINIO_CACHE_AFTER: "3"
      MINIO_CACHE_WATERMARK_LOW: "70"
      MINIO_CACHE_WATERMARK_HIGH: "90"
      MINIO_AUDIT_WEBHOOK_ENABLE_target1: "on"
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1: ""
      MINIO_AUDIT_WEBHOOK_ENDPOINT_target1: http://cwm-worker-logger:8500/logs
      MINIO_GATEWAY_DEPLOYMENT_ID: "docker-compose-http"
      MINIO_API_SELECT_PARQUET: "${MINIO_API_SELECT_PARQUET}"
      MINIO_KMS_AUTO_ENCRYPTION: "off"
      MINIO_KMS_KES_ENDPOINT: "https://minio-kes:7373"
      MINIO_KMS_KES_CERT_FILE: "/kes/certs/minio.cert"
      MINIO_KMS_KES_KEY_FILE: "/kes/certs/minio.key"
      MINIO_KMS_KES_CAPATH: "/kes/certs/server.cert"
      MINIO_KMS_KES_KEY_NAME: minio-encryption-key
    volumes:
      - "storage:/storage"
      - "cache:/cache"
      - "minio-kes-certs:/kes/certs"
    depends_on:
      - minio-kes
      - cwm-worker-logger

  minio-kes:
    image: minio-kes:v0.17.6
    build: ./minio-kes
    container_name: minio-kes
    ports:
      - "7373:7373"
    environment:
      MINIO_KMS_KES_KEY_NAME: minio-encryption-key
    volumes:
      - "minio-kes-certs:/kes/certs"

  cwm-worker-logger:
    image: ghcr.io/cloudwebmanage/cwm-worker-logger/cwm-worker-logger:latest
    ports:
      - "8500:8500"
    environment:
      LOG_PROVIDER: default
      # LOG_PROVIDER: elasticsearch
      # LOG_PROVIDER: s3
      LOG_LEVEL: debug
      # CWM_HTTP_HOST: localhost
      # CWM_HTTP_PORT: 8500
      REDIS_HOST: redis
      # REDIS_PORT: 6379
      # REDIS_DB: 0
      UPDATE_GRACE_PERIOD_SECONDS: 5s
      DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: 5s
      # REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION: deploymentid:last_action
      # REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC: deploymentid:minio-metrics

      # ElasticSearch
      # ES_HOST:
      # ES_PORT:

      # S3
      # AWS_KEY_ID:
      # AWS_SECRET_KEY:
      # S3_BUCKET_NAME:
      # S3_REGION:
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  storage:
  cache:
  minio-kes-certs:
