version: '3.4'

services:

  minio-gateway:
    image: minio
    restart: on-failure
    build: .
    environment:
      MINIO_ROOT_USER: "12345678"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_API_SELECT_PARQUET: "${MINIO_API_SELECT_PARQUET}"
      INSTANCE_TYPE: gateway_azure
      AZURE_STORAGE_ACCOUNT_NAME: "${AZURE_STORAGE_ACCOUNT_NAME}"
      AZURE_STORAGE_ACCOUNT_KEY: "${AZURE_STORAGE_ACCOUNT_KEY}"

  nginx-gateway:
    image: nginx
    restart: on-failure
    build: nginx
    environment:
      HOSTNAMES_DIR: "/hostnames"
      CDN_CACHE_ENABLE: "yes"
      MINIO_PROXY_PASS_HOST: minio-gateway
    ports:
      - "8080:8080"
    volumes:
      - "./tests/hostnames:/hostnames"
    depends_on:
      - minio-gateway
