version: '3.4'

services:

  minio-source:
    # standard minio image pulled on May 19, 2021
    image: minio/minio@sha256:c99efb3042e23fa065738eb100a3484f0dbb6c063844b19a70a31e5231d621b6
    command: [server, /opt]
    environment:
      MINIO_ACCESS_KEY: "accesskey"
      MINIO_SECRET_KEY: "secretkey"

  minio-gateway:
    image: minio
    restart: on-failure
    build: .
    environment:
      MINIO_ACCESS_KEY: "12345678"
      MINIO_SECRET_KEY: "12345678"
      INSTANCE_TYPE: gateway_s3
      GATEWAY_ARGS: "http://minio-source:9000"
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
      MINIO_AUDIT_WEBHOOK_ENABLE_target1: "on"
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1: ""
      MINIO_AUDIT_WEBHOOK_ENDPOINT_target1: http://cwm-worker-logger:8500/logs
      MINIO_GATEWAY_DEPLOYMENT_ID: "docker-compose-http"
    ports:
      - "8080:8080"
    depends_on:
      - minio-source
      - cwm-worker-logger

  cwm-worker-logger:
    image: ghcr.io/cloudwebmanage/cwm-worker-logger/cwm-worker-logger:latest
    ports:
      - "8500:8500"
    environment:
      LOG_PROVIDER: default
      LOG_LEVEL: debug
      REDIS_HOST: redis
      UPDATE_GRACE_PERIOD_SECONDS: 5s
      DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: 5s
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"
