version: '3.4'

services:

  nginx:
    image: nginx
    restart: on-failure
    build: nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      HOSTNAMES_DIR: "/hostnames"
    volumes:
      - "./tests/hostnames:/hostnames"
    depends_on:
      - minio

  minio:
    image: minio
    restart: on-failure
    build: .
    environment:
      MINIO_DOMAIN: "example001.com"
      MINIO_ACCESS_KEY: "12345678"
      MINIO_SECRET_KEY: "12345678"
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/cache"
      MINIO_CACHE_EXCLUDE: "*.pdf"
      MINIO_CACHE_QUOTA: "80"
      MINIO_CACHE_AFTER: "3"
      MINIO_CACHE_WATERMARK_LOW: "70"
      MINIO_CACHE_WATERMARK_HIGH: "90"
      MINIO_AUDIT_WEBHOOK_ENABLE_target1: "on"
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1: ""
      MINIO_AUDIT_WEBHOOK_ENDPOINT_target1: http://cwm-worker-logger:8500/logs
      MINIO_GATEWAY_DEPLOYMENT_ID: "docker-compose-http"
    volumes:
      - "storage:/storage"
      - "cache:/cache"
    depends_on:
      - cwm-worker-logger

  cwm-worker-logger:
    image: docker.pkg.github.com/cloudwebmanage/cwm-worker-logger/cwm-worker-logger:latest
    ports:
      - "8500:8500"
    environment:
      LOG_PROVIDER: default
      # LOG_PROVIDER: elasticsearch
      # LOG_PROVIDER: s3
      LOG_LEVEL: debug
      # CWM_HTTP_HOST: localhost
      # CWM_HTTP_PORT: 8500
      REDIS_HOST: redis
      # REDIS_PORT: 6379
      # REDIS_DB: 0
      UPDATE_GRACE_PERIOD_SECONDS: 5s
      DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: 5s
      # REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION: deploymentid:last_action
      # REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC: deploymentid:minio-metrics

      # ElasticSearch
      # ES_HOST:
      # ES_PORT:

      # S3
      # AWS_KEY_ID:
      # AWS_SECRET_KEY:
      # S3_BUCKET_NAME:
      # S3_REGION:
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  storage:
  cache:
