address: 0.0.0.0:7373

admin:
  identity: disabled

tls:
  key : ${SERVER_KEY_FILE}
  cert: ${SERVER_CERT_FILE}

# kes server will auto-create the keys on startup
# no need to create these manually via kes CLI
keys:
  - name: 'minio'

# define allowed policies for the minio
# with the key already created, only `generate` and `decrypt` are required
policy:
  minio:
    allow:
    - /v1/key/generate/minio
    - /v1/key/decrypt/minio
    identities:
    - ${MINIO_IDENTITY}

log:
  error: on
  audit: on

keystore:
  fs:
    path: ./keys
