address: 0.0.0.0:7373

admin:
  identity: disabled

tls:
  key : ${SERVER_KEY_FILE}
  cert: ${SERVER_CERT_FILE}

policy:
  minio:
    allow:
    - /v1/key/create/minio
    - /v1/key/generate/minio
    - /v1/key/decrypt/minio
    identities:
    - ${MINIO_IDENTITY}

keys:
  - name: 'minio'

log:
  error: on
  audit: on

keystore:
  fs:
    path: ${MINIO_KMS_KES_KEYS_DIR}
