{{ if not .Values.minio.serveSingleProtocolPerPod }}
{{ if .Values.minio.autoscaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: minio
spec:
  minReplicas: {{ .Values.minio.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.minio.autoscaler.maxReplicas }}
  metrics:
{{ .Values.minio.autoscaler.metrics | indent 2 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minio
{{ end }}
{{ end }}
