{{ if $.Values.minio.externalscaler.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-external-scaler
spec:
  podSelector:
    matchLabels:
      app: minio-external-scaler
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 50051
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    {{- if $.Values.minio.metricsLogger.enable }}
    - protocol: TCP
      port: {{ $.Values.minio.metricsLogger.REDIS_PORT }}
    {{- end }}
    # connection to the keda metrics server
    - protocol: TCP
      port: 6443
    - protocol: TCP
      port: 8080
  {{ end }}
