{{- if .Values.minio.metricsLogger.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
data:
  cwm-fluent-default.conf: |
    # fluentd configuration file for CWM HTTP Logging Component for MinIO
    <system>
      log_level             {{ $.Values.minio.metricsLogger.LOG_LEVEL }}
    </system>

    # CWM HTTP input configuration
    <source>
      @type                 http_cwm
      @id                   http_cwm_input_logs

      host                  0.0.0.0
      port                  8500
      tag                   logs

      # CWM Redis instance configuration for metrics
      <redis>
        host                {{ if $.Values.minio.metricsLogger.withRedis }}localhost{{ else }}{{ $.Values.minio.metricsLogger.REDIS_HOST }}{{ end }}
        port                {{ $.Values.minio.metricsLogger.REDIS_PORT }}
        db                  {{ $.Values.minio.metricsLogger.REDIS_DB }}
        grace_period        {{ $.Values.minio.metricsLogger.UPDATE_GRACE_PERIOD_SECONDS }}
        flush_interval      {{ $.Values.minio.metricsLogger.DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS }}
        last_update_prefix  {{ $.Values.minio.metricsLogger.REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION }}
        metrics_prefix      {{ $.Values.minio.metricsLogger.REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC }}
      </redis>
    </source>

  {{- if or (eq $.Values.minio.metricsLogger.LOG_PROVIDER "elasticsearch") (eq $.Values.minio.metricsLogger.LOG_PROVIDER "s3") }}
  cwm-fluent-buffer.conf: |
    # file buffer configurations for output plugins (log targets)
    <buffer>
      @type                 file
      path                  /fluentd/buf/
      path_suffix           .buf

      compress              {{ $.Values.minio.metricsLogger.LOGS_FLUSH_COMPRESSION }}

      flush_at_shutdown     {{ $.Values.minio.metricsLogger.LOGS_FLUSH_AT_SHUTDOWN }}
      flush_mode            interval
      flush_interval        {{ $.Values.minio.metricsLogger.LOGS_FLUSH_INTERVAL }}
      retry_type            periodic
      retry_wait            {{ $.Values.minio.metricsLogger.LOGS_FLUSH_RETRY_WAIT }}

      chunk_limit_size      100m
    </buffer>
  {{- end }}

  {{- if eq $.Values.minio.metricsLogger.LOG_PROVIDER "stdout" }}
  cwm-fluent-stdout.conf: |
    @include                ./cwm-fluent-default.conf
    <match logs>
      @type                 stdout
    </match>
  {{- end }}

  {{- if eq $.Values.minio.metricsLogger.LOG_PROVIDER "elasticsearch" }}
  cwm-fluent-elasticsearch.conf: |
    @include                ./cwm-fluent-default.conf
    # ElasticSearch: https://docs.fluentd.org/output/elasticsearch
    <match logs>
      @type                 elasticsearch
      @id                   elasticsearch_log_target

      {{- if not $.Values.minio.metricsLogger.ES_MULTIPLE_HOSTS_ENABLED }}
      host                  {{ $.Values.minio.metricsLogger.ES_HOST }}
      port                  {{ $.Values.minio.metricsLogger.ES_PORT }}
      {{ else if $.Values.minio.metricsLogger.ES_HOSTS }}
        {{- $hosts := ($.Values.minio.metricsLogger.ES_HOSTS | replace " " "") }}
        {{- if (eq $.Values.minio.metricsLogger.ES_SCHEME "https") }}
          {{- $hosts = ($hosts | replace "https://" "") }}
        {{- end }}
      hosts                 {{ $hosts }}
      {{- end }}

      scheme                {{ $.Values.minio.metricsLogger.ES_SCHEME }}
      ssl_verify            {{ $.Values.minio.metricsLogger.ES_SSL_VERIFY }}

      {{- if $.Values.minio.metricsLogger.ES_AUTH_ENABLED }}
      user                  {{ $.Values.minio.metricsLogger.ES_USERNAME }}
      password              {{ $.Values.minio.metricsLogger.ES_PASSWORD }}
      {{- end }}

      index_name            {{ $.Values.minio.metricsLogger.ES_INDEX_NAME }}
      type_name             {{ $.Values.minio.metricsLogger.ES_TYPE_NAME }}

      {{- if $.Values.minio.metricsLogger.ES_INDEX_NAME }}
      {{- if $.Values.minio.metricsLogger.ES_PATH }}
      path                  {{ $.Values.minio.metricsLogger.ES_PATH }}
      {{- end }}
      {{- end }}

      # Timeout issue: https://github.com/uken/fluent-plugin-elasticsearch/issues/590
      request_timeout       2147483648

      @include              ./cwm-fluent-buffer.conf
    </match>
  {{- end }}

  {{- if eq $.Values.minio.metricsLogger.LOG_PROVIDER "s3" }}
  cwm-fluent-s3.conf: |
    @include                ./cwm-fluent-default.conf
    # S3: https://docs.fluentd.org/output/s3
    <match logs>
      @type                 s3
      @id                   s3_log_target

      aws_key_id            {{ $.Values.minio.metricsLogger.AWS_KEY_ID }}
      aws_sec_key           {{ $.Values.minio.metricsLogger.AWS_SECRET_KEY }}
      s3_bucket             {{ $.Values.minio.metricsLogger.S3_BUCKET }}
      s3_region             {{ $.Values.minio.metricsLogger.S3_REGION }}
      path                  {{ $.Values.minio.metricsLogger.S3_PATH }}

      {{- if $.Values.minio.metricsLogger.S3_NON_AWS_TARGET }}
      s3_endpoint           {{ $.Values.minio.metricsLogger.S3_ENDPOINT }}
      force_path_style      true
      {{- end }}

      ssl_verify_peer       {{ $.Values.minio.metricsLogger.S3_SSL_VERIFY }}

      time_slice_format     %Y%m%d%H%M
      s3_object_key_format  %{path}%{time_slice}_%{index}.%{file_extension}

      # Compression Type: gzip (default), lzo, json, txt
      store_as              {{ $.Values.minio.metricsLogger.S3_STORE_AS }}

      @include              ./cwm-fluent-buffer.conf
    </match>
  {{- end }}
{{- end }}
