{{- if .Values.minio.metricsLogger.enable }}
apiVersion: v1
kind: Service
metadata:
  name: minio-logger
spec:
  ports:
  - name: "8500"
    port: 8500
  {{- if $.Values.minio.metricsLogger.withRedis }}
  - name: "6379"
    port: 6379
  {{- end }}
  selector:
    app: minio-logger
{{- end }}
