apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
data:
  cwm-fluent-default.conf: |
    # fluentd configuration file for CWM HTTP Logging Component for MinIO
    <system>
      log_level             debug
    </system>
    # CWM HTTP input configuration
    <source>
      @type                 http_cwm
      @id                   http_cwm_input_logs

      host                  0.0.0.0
      port                  8500
      tag                   logs

      # CWM Redis instance configuration for metrics
      <redis>
        host                localhost
        port                6379
        grace_period        10s
        flush_interval      2s
        last_update_prefix  deploymentid:last_action
        metrics_prefix      deploymentid:minio-metrics
      </redis>
    </source>

  cwm-fluent-buffer.conf: |
    # file buffer configurations for output plugins (log targets)
    <buffer>
      @type                 file

      path                  /fluentd/buf/
      path_suffix           .buf
      compress              gzip

      flush_at_shutdown     true
      flush_mode            interval
      flush_interval        10s
      retry_type            periodic
      retry_wait            10s
    </buffer>

  cwm-fluent-stdout.conf: |
    @include                ./cwm-fluent-default.conf
    <match logs>
      @type                 stdout
    </match>

  cwm-fluent-elasticsearch.conf: |
    @include                ./cwm-fluent-default.conf
    # ElasticSearch: https://docs.fluentd.org/output/elasticsearch
    <match logs>
      @type                 elasticsearch
      @id                   elasticsearch_log_target

      host                  0.0.0.0
      port                  9200
      scheme                http

      ssl_verify            true
      # hosts                 '0.0.0.0:9200'

      # user                  dummyuser
      # password              dummypassword

      index_name            test
      # index_type            _doc

      # NOTE: The index must already exist! DO NOT add a trailing slash!
      # path                  /index/path

      # Timeout issue: https://github.com/uken/fluent-plugin-elasticsearch/issues/590
      request_timeout       2147483648

      @include              ./cwm-fluent-buffer.conf
    </match>

  cwm-fluent-s3.conf: |
    @include                ./cwm-fluent-default.conf
    # S3: https://docs.fluentd.org/output/s3
    <match logs>
      @type                 s3
      @id                   s3_log_target

      # AWS S3 configuration
      # --------------------
      # aws_key_id            "#{ ENV['AWS_KEY_ID'] || 'dummykey' }"
      # aws_sec_key           "#{ ENV['AWS_SECRET_KEY'] || 'dummypass' }"
      # s3_bucket             "#{ ENV['S3_BUCKET_NAME'] || 'test123' }"
      # s3_region             "#{ ENV['S3_REGION'] || 'us-east-1' }"
      # path                  "#{ ENV['S3_PATH'] || 'logs/' }"

      # S3 compatible service configuration
      # -----------------------------------
      # aws_key_id            dummykey
      # aws_sec_key           dummypass
      # s3_bucket             'test123'
      # s3_region             us-east-1
      # path                  logs/
      # s3_endpoint           http://localhost:8080

      # ssl_verify_peer       true

      # Compression Type: gzip (default), lzo, json, txt
      # store_as              gzip

      # s3_object_key_format  %{path}%{time_slice}_%{index}.%{file_extension}

      # auto_create_bucket    true

      @include              ./cwm-fluent-buffer.conf
    </match>
