{{ if .Values.minio.serveSingleProtocolPerPod }}
{{ if .Values.minio.metricsLogger.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-logger
spec:
  replicas: 1
  revisionHistoryLimit: {{ $.Values.minio.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: minio-logger
  template:
    metadata:
      labels:
        app: minio-logger
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      {{ $.Values.minio.imagePullSecrets | indent 6 }}
      terminationGracePeriodSeconds: {{ $.Values.minio.terminationGracePeriodSeconds }}
      automountServiceAccountToken: false
      {{ if $.Values.minio.nodeSelector }}
      nodeSelector:
{{ $.Values.minio.nodeSelector | indent 8 }}
      {{ end }}
      {{- if $.Values.minio.tolerations }}
      tolerations:
{{ toYaml $.Values.minio.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: logger
        image: {{ $.Values.minio.metricsLogger.image }}
        imagePullPolicy: {{ $.Values.minio.metricsLogger.imagePullPolicy }}
        resources:
{{ toYaml $.Values.minio.metricsLogger.resources | indent 10 }}
        env:
        - name: LOG_PROVIDER
          value: {{ $.Values.minio.metricsLogger.LOG_PROVIDER | default "default" | quote }}
        - name: LOG_LEVEL
          value: {{ $.Values.minio.metricsLogger.LOG_LEVEL | quote }}
        - name: REDIS_HOST
          value: {{ $.Values.minio.metricsLogger.REDIS_HOST | quote }}
        - name: REDIS_PORT
          value: {{ $.Values.minio.metricsLogger.REDIS_PORT | quote }}
        - name: UPDATE_GRACE_PERIOD_SECONDS
          value: {{ $.Values.minio.metricsLogger.UPDATE_GRACE_PERIOD_SECONDS | quote }}
        - name: DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS
          value: {{ $.Values.minio.metricsLogger.DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS | quote }}
        - name: REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION
          value: {{ $.Values.minio.metricsLogger.REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION | quote }}
        - name: REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC
          value: {{ $.Values.minio.metricsLogger.REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC | quote }}
        {{ if $.Values.minio.metricsLogger.LOG_PROVIDER }}
        {{ if eq $.Values.minio.metricsLogger.LOG_PROVIDER "elasticsearch" }}
        - name: ES_HOST
          value: {{ $.Values.minio.metricsLogger.ES_HOST | quote }}
        - name: ES_PORT
          value: {{ $.Values.minio.metricsLogger.ES_PORT | quote }}
        {{ else if eq $.Values.minio.metricsLogger.LOG_PROVIDER "s3" }}
        - name: AWS_KEY_ID
          value: {{ $.Values.minio.metricsLogger.AWS_KEY_ID | quote }}
        - name: AWS_SECRET_KEY
          value: {{ $.Values.minio.metricsLogger.AWS_SECRET_KEY | quote }}
        - name: S3_BUCKET_NAME
          value: {{ $.Values.minio.metricsLogger.S3_BUCKET_NAME | quote }}
        - name: S3_REGION
          value: {{ $.Values.minio.metricsLogger.S3_REGION | quote }}
        - name: S3_PATH
          value: {{ $.Values.minio.metricsLogger.S3_PATH | quote }}
        {{ end }}
        {{ end }}
      {{ if $.Values.minio.metricsLogger.withRedis }}
      - name: redis
        image: redis
      {{ end }}
{{ end }}
{{ end }}
