apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
data:
  cwm-fluent-default.conf: |
    # fluentd configuration file for CWM HTTP Logging Component for MinIO
    <system>
      log_level             "#{ ENV['LOG_LEVEL'] || 'info' }"
    </system>

    # CWM HTTP input configuration
    <source>
      @type                 http_cwm
      @id                   http_cwm_input_logs

      host                  "#{ ENV['CWM_HTTP_HOST'] || '0.0.0.0' }"
      port                  "#{ ENV['CWM_HTTP_PORT'] || '8500' }"
      tag                   logs

      # CWM Redis instance configuration for metrics
      <redis>
        host                "#{ ENV['REDIS_HOST'] || 'localhost' }"
        port                "#{ ENV['REDIS_PORT'] || '6379' }"
        grace_period        "#{ ENV['UPDATE_GRACE_PERIOD_SECONDS'] || '300s' }"
        flush_interval      "#{ ENV['DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS'] || '300s' }"
        last_update_prefix  "#{ ENV['REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION'] || 'deploymentid:last_action' }"
        metrics_prefix      "#{ ENV['REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC'] || 'deploymentid:minio-metrics' }"
      </redis>
    </source>

  cwm-fluent-stdout.conf: |
    @include ./cwm-fluent-default.conf
    <match logs>
      @type                 stdout
      @id                   stdout_log_target
    </match>

  cwm-fluent-buffer.conf: |
    # file buffer configurations for output plugins (log targets)
    <buffer>
      @type                 file

      path                  /var/log/fluentd/cwm-worker-logger
      path_suffix           .buf

      compress              gzip

      flush_at_shutdown     "#{ ENV['LOGS_FLUSH_AT_SHUTDOWN'] || 'false' }"
      flush_mode            interval
      flush_interval        "#{ ENV['LOGS_FLUSH_INTERVAL'] || '60s' }"

      retry_type            periodic
      retry_wait            "#{ ENV['LOGS_RETRY_WAIT'] || '20s' }"
    </buffer>

  cwm-fluent-elasticsearch.conf: |
    @include                ./cwm-fluent-default.conf

    # ElasticSearch: https://docs.fluentd.org/output/elasticsearch
    <match logs>
      @type                 elasticsearch
      @id                   elasticsearch_log_target

      host                  "#{ ENV['ES_HOST'] || '0.0.0.0' }"
      port                  "#{ ENV['ES_PORT'] || '9200' }"
      logstash_format       true

      @include              ./cwm-fluent-buffer.conf
    </match>

  cwm-fluent-s3.conf: |
    @include ./cwm-fluent-default.conf

    # S3: https://docs.fluentd.org/output/s3
    <match logs>
      @type                 s3
      @id                   s3_log_target

      aws_key_id            "#{ ENV['AWS_KEY_ID'] || '' }"
      aws_sec_key           "#{ ENV['AWS_SECRET_KEY'] || '' }"
      s3_bucket             "#{ ENV['S3_BUCKET_NAME'] || '' }"
      s3_region             "#{ ENV['S3_REGION'] || '' }"
      path                  "#{ ENV['S3_PATH'] || 'logs/' }"

      @include              ./cwm-fluent-buffer.conf
    </match>
