{{ if .Values.minio.metricsLogger.enable }}
apiVersion: v1
kind: Service
metadata:
  name: minio-logger
spec:
  ports:
  - name: "8500"
    port: 8500
  - name: "6379"
    port: 6379
  selector:
    app: minio-logger
{{ end }}
