{{ if .Values.minio.metricsLogger.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-logger
spec:
  podSelector:
    matchLabels:
      app: minio-logger
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: minio
    ports:
    - protocol: TCP
      port: 8500
  {{- if not $.Values.minio.metricsLogger.withRedis }}
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: {{ $.Values.minio.metricsLogger.REDIS_PORT }}
  {{- end }}
{{ end }}
