{{- if .Values.minio.metricsLogger.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-logger
spec:
  replicas: 1
  revisionHistoryLimit: {{ $.Values.minio.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: minio-logger
  template:
    metadata:
      labels:
        app: minio-logger
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/logger-configmap.yaml") . | sha256sum }}
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: {{ $.Values.minio.metricsLogger.terminationGracePeriodSeconds }}
      automountServiceAccountToken: false
      {{- if $.Values.minio.nodeSelector }}
      nodeSelector: {{ $.Values.minio.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $.Values.minio.tolerations }}
      tolerations: {{ toYaml $.Values.minio.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: logger
        image: {{ $.Values.minio.metricsLogger.image }}
        lifecycle: {preStop: {exec: {command: ["sleep", {{ $.Values.minio.metricsLogger.preStopDelaySeconds | quote }}]}}}
        imagePullPolicy: {{ $.Values.minio.metricsLogger.imagePullPolicy }}
        resources: {{ toYaml $.Values.minio.metricsLogger.resources | nindent 10 }}
        volumeMounts:
        - name: "fluentd-conf-volume"
          mountPath: "/fluentd/etc/"
          readOnly: true
        env:
        - name: LOG_PROVIDER
          value: {{ $.Values.minio.metricsLogger.LOG_PROVIDER | default "default" | quote }}
      {{- if $.Values.minio.metricsLogger.withRedis }}
      - name: redis
        image: redis
      {{- end }}
      volumes:
      - name: fluentd-conf-volume
        configMap:
          name: fluentd-conf
{{- end }}
