{{- if .Values.minio.metricsLogger.externalscaler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-logger-external-scaler
spec:
  replicas: 1
  revisionHistoryLimit: {{ $.Values.minio.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: minio-logger-external-scaler
  template:
    metadata:
      labels:
        app: minio-logger-external-scaler
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets: {{ $.Values.minio.imagePullSecrets | nindent 6 }}
      terminationGracePeriodSeconds: {{ $.Values.minio.terminationGracePeriodSeconds }}
      automountServiceAccountToken: false
      {{- if $.Values.minio.nodeSelector }}
      nodeSelector: {{ $.Values.minio.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $.Values.minio.tolerations }}
      tolerations: {{ toYaml $.Values.minio.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: minio-logger-external-scaler
        image: {{ $.Values.minio.metricsLogger.externalscaler.image }}
        imagePullPolicy: {{ $.Values.minio.metricsLogger.externalscaler.imagePullPolicy }}
        resources: {{ toYaml $.Values.minio.metricsLogger.externalscaler.resources | nindent 10 }}
        env:
        - name: CWM_REDIS_HOST
          value: {{ $.Values.minio.metricsLogger.REDIS_HOST | quote }}
        - name: CWM_REDIS_PORT
          value: {{ $.Values.minio.metricsLogger.REDIS_PORT | quote }}
        - name: CWM_REDIS_DB
          value: {{ $.Values.minio.metricsLogger.REDIS_DB | quote }}
        - name: LAST_UPDATE_PREFIX
          value: {{ $.Values.minio.metricsLogger.REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION | quote }}
        - name: METRICS_PREFIX
          value: {{ $.Values.minio.metricsLogger.REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC | quote }}
{{- end }}
