apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio
spec:
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    - podSelector:
        matchLabels:
          app: nginx
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 8080
    {{- if .Values.minio.metricsLogger.enable }}
    - protocol: TCP
      port: 8500
    {{- end }}
