{{ if .Values.minio.enableServiceMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-node-monitor
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: minio
  endpoints:
  - port: "8080"
    path: /minio/v2/metrics/node
{{ end }}
