apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-nginx
spec:
  replicas: {{ $.Values.minio.nginx.replicas }}
  revisionHistoryLimit: {{ $.Values.minio.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: minio-nginx
  strategy: {{ toYaml $.Values.minio.nginx.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: minio-nginx
        cwm-worker-deployment: minio
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-hostnames-configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          {{ if $.Values.minio.nginx.enableNginxAntiAffinityRequired }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: minio-nginx
          {{ end }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    cwm-worker-deployment: minio
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: {{ $.Values.minio.nginx.terminationGracePeriodSeconds }}
      automountServiceAccountToken: false
      {{- if $.Values.minio.nodeSelector }}
      nodeSelector: {{ $.Values.minio.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $.Values.minio.tolerations }}
      tolerations: {{ toYaml $.Values.minio.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: nginx
        image: {{ $.Values.minio.nginx.image }}:{{ $.Values.minio.nginx.tag | default $.Chart.AppVersion }}
        lifecycle: {preStop: {exec: {command: ["sleep", {{ $.Values.minio.nginx.preStopDelaySeconds | quote }}]}}}
        imagePullPolicy: {{ $.Values.minio.imagePullPolicy }}
        env:
          - name: HOSTNAMES_DIR
            value: "/hostnames"
          - name: MINIO_PROXY_PASS_HOST
            value: "minio-server"
          - name: DISABLE_HTTP
            value: {{ $.Values.minio.nginx.DISABLE_HTTP | quote }}
          - name: DISABLE_HTTPS
            value: {{ $.Values.minio.nginx.DISABLE_HTTPS | quote }}
          {{- if $.Values.minio.nginx.CDN_CACHE_ENABLE }}
          - name: CDN_CACHE_ENABLE
            value: "yes"
          - name: CDN_CACHE_PROXY_PATH
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_PATH | quote }}
          - name: CDN_CACHE_PROXY_KEYS_MAX_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_KEYS_MAX_SIZE | quote }}
          - name: CDN_CACHE_PROXY_MAX_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_MAX_SIZE | quote }}
          - name: CDN_CACHE_PROXY_INACTIVE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_INACTIVE | quote }}
          - name: CDN_CACHE_PROXY_TEMP_PATH
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_TEMP_PATH | quote }}
          - name: CDN_CACHE_PROXY_BUFFERS
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_BUFFERS | quote }}
          - name: CDN_CACHE_PROXY_BUFFER_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_BUFFER_SIZE | quote }}
          - name: CDN_CACHE_PROXY_BUSY_BUFFERS_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_BUSY_BUFFERS_SIZE | quote }}
          - name: CDN_CACHE_PROXY_CACHE_VALID_200
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_CACHE_VALID_200 | quote }}
          - name: CDN_CACHE_NOCACHE_REGEX
            value: {{ $.Values.minio.nginx.CDN_CACHE_NOCACHE_REGEX | quote }}
          {{- end }}
          {{ if $.Values.minio.nginx.ENABLE_ACCESS_LOG }}
          - name: ENABLE_ACCESS_LOG
            value: "yes"
          {{ end }}
          {{ if $.Values.minio.nginx.NGINX_ERROR_LEVEL }}
          - name: NGINX_ERROR_LEVEL
            value: {{ $.Values.minio.nginx.NGINX_ERROR_LEVEL | quote }}
          {{ end }}
          {{ if $.Values.minio.nginx.NGINX_DEBUG }}
          - name: NGINX_DEBUG
            value: "yes"
          {{ end }}
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {{ toYaml $.Values.minio.nginx.resources | nindent 10 }}
        volumeMounts:
        - name: hostnames
          mountPath: /hostnames
        {{- if $.Values.minio.nginx.CDN_CACHE_ENABLE }}
        - mountPath: {{ $.Values.minio.nginx.cacheVolumeMountPath | quote }}
          name: "cache"
          {{ if $.Values.minio.nginx.cacheVolumeSubPath }}
          subPath: {{ $.Values.minio.nginx.cacheVolumeSubPath | quote }}
          {{ end }}
        {{- end }}
      volumes:
      - name: hostnames
        configMap:
          name: nginx-hostnames
      {{- if $.Values.minio.nginx.CDN_CACHE_ENABLE }}
      - name: cache
        {{- if $.Values.minio.nginx.cacheVolume }}
{{ toYaml $.Values.minio.nginx.cacheVolume | indent 8 }}
        {{- else if $.Values.minio.volumes.cache }}
{{ toYaml $.Values.minio.volumes.cache | indent 8 }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- end }}
