apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-hostnames
data:
{{ range $.Values.minio.nginx.hostnames }}
  {{ .id }}.name: {{ .name }}
  {{ if and .pem .key }}
  {{ .id }}.pem: {{ .pem | quote }}
  {{ .id }}.key: {{ .key | quote }}
  {{ end }}
  {{ if and .cc_token .cc_payload }}
  {{ .id }}.cc_token: {{ .cc_token | quote }}
  {{ .id }}.cc_payload: {{ .cc_payload | quote }}
  {{ end }}
{{ end }}
