apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-nginx
spec:
  replicas: {{ $.Values.minio.nginx.replicas }}
  revisionHistoryLimit: {{ $.Values.minio.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: minio-nginx
  strategy: {{ toYaml $.Values.minio.nginx.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: minio-nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-hostnames-configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: nginx
      dnsPolicy: ClusterFirst
      imagePullSecrets: {{ $.Values.minio.imagePullSecrets | nindent 6 }}
      terminationGracePeriodSeconds: {{ $.Values.minio.terminationGracePeriodSeconds }}
      automountServiceAccountToken: false
      {{- if $.Values.minio.nodeSelector }}
      nodeSelector: {{ $.Values.minio.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $.Values.minio.tolerations }}
      tolerations: {{ toYaml $.Values.minio.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: nginx
        image: {{ $.Values.minio.nginx.image }}:{{ $.Values.minio.nginx.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ $.Values.minio.imagePullPolicy }}
        env:
          - name: HOSTNAMES_DIR
            value: "/hostnames"
          - name: MINIO_PROXY_PASS_HOST
            value: "minio-server"
          - name: DISABLE_HTTP
            value: {{ $.Values.minio.nginx.disableHttp | quote }}
          - name: DISABLE_HTTPS
            value: {{ $.Values.minio.nginx.disableHttps | quote }}
          {{ if $.Values.minio.nginx.CDN_CACHE_ENABLE }}
          - name: CDN_CACHE_ENABLE
            value: "yes"
          - name: CDN_CACHE_PROXY_PATH
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_PATH | quote }}
          - name: CDN_CACHE_PROXY_KEYS_MAX_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_KEYS_MAX_SIZE | quote }}
          - name: CDN_CACHE_PROXY_MAX_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_MAX_SIZE | quote }}
          - name: CDN_CACHE_PROXY_INACTIVE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_INACTIVE | quote }}
          - name: CDN_CACHE_PROXY_TEMP_PATH
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_TEMP_PATH | quote }}
          - name: CDN_CACHE_PROXY_BUFFERS
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_BUFFERS | quote }}
          - name: CDN_CACHE_PROXY_BUFFER_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_BUFFER_SIZE | quote }}
          - name: CDN_CACHE_PROXY_BUSY_BUFFERS_SIZE
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_BUSY_BUFFERS_SIZE | quote }}
          - name: CDN_CACHE_PROXY_CACHE_VALID_200
            value: {{ $.Values.minio.nginx.CDN_CACHE_PROXY_CACHE_VALID_200 | quote }}
          - name: CDN_CACHE_NOCACHE_REGEX
            value: {{ $.Values.minio.nginx.CDN_CACHE_NOCACHE_REGEX | quote }}
          {{ end }}
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {{ toYaml $.Values.minio.nginx.resources | nindent 10 }}
        volumeMounts:
        - name: hostnames
          mountPath: /hostnames
        {{ if $.Values.minio.nginx.CDN_CACHE_ENABLE }}
        - mountPath: {{ $.Values.minio.nginx.cacheVolumeMountPath | quote }}
          name: "cache"
          subPath: {{ $.Values.minio.nginx.cacheVolumeSubPath | quote }}
        {{ end }}
      volumes:
      - name: hostnames
        configMap:
          name: nginx-hostnames
      {{ if $.Values.minio.nginx.CDN_CACHE_ENABLE }}
      - name: cache
{{ $.Values.minio.volumes.cache | indent 8 }}
      {{ end }}
