apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ $.Values.minio.nginx.replicas }}
  revisionHistoryLimit: {{ $.Values.minio.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: nginx
  strategy: {{ toYaml $.Values.minio.nginx.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-hostnames-configmap.yaml") . | sha256sum }}
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets: {{ $.Values.minio.imagePullSecrets | nindent 6 }}
      terminationGracePeriodSeconds: {{ $.Values.minio.terminationGracePeriodSeconds }}
      automountServiceAccountToken: false
      {{- if $.Values.minio.nodeSelector }}
      nodeSelector: {{ $.Values.minio.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $.Values.minio.tolerations }}
      tolerations: {{ toYaml $.Values.minio.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: nginx
        image: {{ $.Values.minio.nginx.image }}:{{ $.Values.minio.nginx.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ $.Values.minio.imagePullPolicy }}
        env:
          - name: HOSTNAMES_DIR
            value: "/hostnames"
          - name: DISABLE_HTTP
            value: {{ $.Values.minio.nginx.disableHttp | quote }}
          - name: DISABLE_HTTPS
            value: {{ $.Values.minio.nginx.disableHttps | quote }}
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {{ toYaml $.Values.minio.nginx.resources | nindent 10 }}
        volumeMounts:
        - name: hostnames
          mountPath: /hostnames
      volumes:
      - name: hostnames
        configMap:
          name: nginx-hostnames
