{{ if .Values.minio.createPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: github
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.minio.createPullSecret | b64enc | quote }}
{{ end }}
