{{ if $.Values.minio.externalscaler.enabled }}
{{ if $.Values.minio.scaledobject.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: minio-server
spec: {{ toYaml $.Values.minio.scaledobject.spec | nindent 2 }}
{{ end }}
{{ end }}
