apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-server
spec:
  podSelector:
    matchLabels:
      app: minio-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: minio-nginx
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 8080
    {{- if .Values.minio.metricsLogger.enable }}
    - protocol: TCP
      port: 8500
    {{- end }}
    {{- if $.Values.minio.INSTANCE_TYPE }}
    {{- range $.Values.minio.gatewayNetworkPolicyExtraEgressPorts }}
    - protocol: TCP
      port: {{ . }}
    {{- end }}
    {{- end }}
