{{ if .Values.minio.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: "8080"
    port: 8080
  - name: "8443"
    port: 8443
  selector:
    app: minio
{{ end }}
