{{ range $.Values.tenants }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name }}-env-configuration
  namespace: {{ .name }}
stringData:
  config.env: |
    export MINIO_BROWSER="on"
    export MINIO_ROOT_USER={{ .root_user | quote }}
    export MINIO_ROOT_PASSWORD={{ .root_password | quote }}
    export MINIO_STORAGE_CLASS_STANDARD={{ .storage_class_standard | quote }}
    export MINIO_DOMAIN="minio-tenant-{{ .name }}{{ .domain_suffix }}"
    export MINIO_BROWSER_REDIRECT_URL="https://minio-tenant-{{ .name }}-console{{ .domain_suffix }}"
    export MINIO_SERVER_URL="https://minio-tenant-{{ .name }}{{ .domain_suffix }}"
---
{{ end }}
