{{ range $.Values.tenants }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: storage-user
  namespace: {{ .name }}
stringData:
  CONSOLE_ACCESS_KEY: {{ .user_user | quote }}
  CONSOLE_SECRET_KEY: {{ .user_password | quote }}
---
{{ end }}
