{{ range $.Values.tenants }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name }}-secret
  namespace: {{ .name }}
stringData:
  accesskey: {{ .root_user | quote }}
  secretkey: {{ .root_password | quote }}
---
{{ end }}
