minio:
  replicas: 1
  revisionHistoryLimit: 2
  terminationGracePeriodSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  nodeSelector: ""
  # tolerations: []
  image: ghcr.io/cloudwebmanage/cwm-worker-deployment-minio/minio
  tag: ""
  imagePullPolicy: IfNotPresent
  auditWebhookEndpoint: "http://minio-logger:8500/logs"
  skipWaitForAuditWebhook: false
  MINIO_GATEWAY_DEPLOYMENT_ID: "minio1"
  MINIO_EXTRA_ARGS: ""
  initDebugEnable: false
  initCurlMaxTime: "1.5"
  # this exposes prometheus metrics unauthenticated at /minio/v2/metrics/cluster and /minio/v2/metrics/node
  enablePrometheusAuthTypePublic: true
  # it requires prometheus operator version 0.45 (kube-prometheus-stack 13.13)
  enableServiceMonitors: false

  # to enable gateway instance, set INSTANCE_TYPE to one of gateway_s3 / gateway_gcs / gateway_azure
  INSTANCE_TYPE: ""
  # when using gateway instance you need to also set appropriate ports to open in network policy
  # this is only used if INSTANCE_TYPE value is provided
  gatewayNetworkPolicyExtraEgressPorts: [ 443 ]
  # when INSTANCE_TYPE is enabled the following values should also be provided depending on the gateway type:
  #   for gateway_s3: GATEWAY_ARGS should be the URL of the source s3 endpoint (or keep empty to use AWS S3)
  #                   AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are the credentials for the source instance
  #   for gateway_gcs: GATEWAY_ARGS should be the google project id
  #                    GOOGLE_APPLICATION_CREDENTIALS should contain the google credentials (as a yaml map)
  #   for gateway_azure: AZURE_STORAGE_ACCOUNT_NAME / AZURE_STORAGE_ACCOUNT_KEY should be set
  GATEWAY_ARGS: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  GOOGLE_APPLICATION_CREDENTIALS: {}
  AZURE_STORAGE_ACCOUNT_NAME: ""
  AZURE_STORAGE_ACCOUNT_KEY: ""

  startupProbe:
    path: /minio/health/live
    initialDelaySeconds: 1
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 2
    curlMaxTimeSeconds: "0.9"
    curlConnectTimeoutSeconds: "0.2"
  livenessProbe:
    path: /minio/health/live
    initialDelaySeconds: 1
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 2
    curlMaxTimeSeconds: "0.9"
    curlConnectTimeoutSeconds: "0.2"
  readinessProbe:
    path: /minio/health/ready
    initialDelaySeconds: 1
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 2
    curlMaxTimeSeconds: "0.9"
    curlConnectTimeoutSeconds: "0.2"
  resources:
    requests:
      cpu: "50m"
      memory: "200Mi"
    limits:
      memory: "200Mi"
  cache:
    enabled: true
    drives: "/cache"
    exclude: "*.pdf"
    quota: 80
    after: 3
    watermark_low: 70
    watermark_high: 90
  browser: true
  access_key: "dummykey"
  secret_key: "dummypass"
  storageVolumeSubPath: ""
  cacheVolumeSubPath: ""
  volumes:
    storage: null
    cache: null

  externalscaler:
    enabled: false
    image: ghcr.io/cloudwebmanage/cwm-keda-external-scaler
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "20m"
        memory: "64Mi"
      limits:
        memory: "150Mi"

  # External: https://github.com/cloudwebmanage/cwm-keda-external-scaler
  # CPU: https://keda.sh/docs/2.3/scalers/cpu/
  # Memory: https://keda.sh/docs/2.3/scalers/memory/
  scaledobject:
    enabled: false
    type: external          # external, cpu, memory
    # external
    pollingInterval: 10
    cooldownPeriod:  60
    minReplicaCount: 1
    maxReplicaCount: 10
    # advanced:
    #   restoreToOriginalReplicaCount: true
    #   horizontalPodAutoscalerConfig:
    #     behavior:
    #       scaleDown:
    #         stabilizationWindowSeconds: 30
    #         policies:
    #         - type: Percent
    #           value: 80
    #           periodSeconds: 15
    isActiveTtlSeconds: "60"
    scalePeriodSeconds: "60"
    scaleMetricName: "num_requests_misc"
    targetValue: "10"
    # cpu / memory
    metricType: Utilization # Utilization, Value, AverageValue
    metricValue: "80"

  metricsLogger:
    enable: true
    image: ghcr.io/cloudwebmanage/cwm-worker-logger/cwm-worker-logger
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "20m"
        memory: "64Mi"
      limits:
        memory: "150Mi"
    withRedis: true
    LOG_PROVIDER: default
    # LOG_PROVIDER: stdout
    LOG_LEVEL: info           # fatal, error, warn, info, debug, trace

    # Redis configuration
    REDIS_HOST: minio-logger
    REDIS_PORT: 6379
    REDIS_DB: 0
    UPDATE_GRACE_PERIOD_SECONDS: 300s
    DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: 300s
    REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION: deploymentid:last_action
    REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC: deploymentid:minio-metrics

    # Logs buffering/flushing configuration
    LOGS_FLUSH_COMPRESSION: gzip
    LOGS_FLUSH_AT_SHUTDOWN: true
    LOGS_FLUSH_INTERVAL: 60s
    LOGS_FLUSH_RETRY_WAIT: 20s

    # LOG_PROVIDER: elasticsearch
    ES_HOST: 0.0.0.0
    ES_PORT: 9200
    ES_SCHEME: http
    ES_MULTIPLE_HOSTS_ENABLED: false
    ES_HOSTS: '0.0.0.0:9200'
    ES_SSL_VERIFY: true
    ES_AUTH_ENABLED: false
    ES_USERNAME: dummykey
    ES_PASSWORD: dummypass
    ES_INDEX_NAME: test
    ES_TYPE_NAME: _doc
    ES_PATH: /logs            # NOTE: The index must already exist! DO NOT add a trailing slash!

    # LOG_PROVIDER: s3
    AWS_KEY_ID: dummykey
    AWS_SECRET_KEY: dummypass
    S3_BUCKET: test123
    S3_REGION: us-east-1
    S3_PATH: logs/
    S3_NON_AWS_TARGET: false
    S3_ENDPOINT: http://localhost:8080
    S3_SSL_VERIFY: true
    S3_STORE_AS: gzip         # gzip, lzo, json, txt

    # External: https://github.com/cloudwebmanage/cwm-keda-external-scaler
    # CPU: https://keda.sh/docs/2.3/scalers/cpu/
    # Memory: https://keda.sh/docs/2.3/scalers/memory/
    scaledobject:
      enabled: false
      type: external          # external, cpu, memory
      # external
      pollingInterval: 10
      cooldownPeriod:  60
      minReplicaCount: 1
      maxReplicaCount: 10
      # advanced:
      #   restoreToOriginalReplicaCount: true
      #   horizontalPodAutoscalerConfig:
      #     behavior:
      #       scaleDown:
      #         stabilizationWindowSeconds: 30
      #         policies:
      #         - type: Percent
      #           value: 80
      #           periodSeconds: 15
      isActiveTtlSeconds: "60"
      scalePeriodSeconds: "60"
      scaleMetricName: "num_requests_misc"
      targetValue: "10"
      # cpu / memory
      metricType: Utilization # Utilization, Value, AverageValue
      metricValue: "80"

  nginx:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    image: ghcr.io/cloudwebmanage/cwm-worker-deployment-minio/minio-nginx
    tag: ""
    resources:
      requests:
        cpu: "25m"
        memory: "50Mi"
      limits:
        memory: "150Mi"
    # copied from tests/hostnames/dhparam.pem
    dhparam_key: |
      -----BEGIN DH PARAMETERS-----
      MIIBCAKCAQEAuueQU6VmApLtG08PRJiq5nBrBPoieQ0MhAI3jZAuahu0AnQ/nnio
      aIfCvnnwilebPID8/a9iFzzqkcZWwAK/OaYn2p6t/9mfyYFVkWI394rCXTjXp8qa
      l5fl0cEzQT5erIi+UKKjFw1jirmigriLPzM+JvZUTzvkpeI7QNiFirg6Oq6IZiM+
      +sIqeaCWA3ughSIzcKQ/w6qNjPTrDHbxc41AZS1o5xzngmMGHBl0Nw7kvd0b6tZN
      I1ZLzZKeEApAE5f8z8eDdGXDbHaCd7bs9qhak7xUQNs8wEomV8F8rYDBnCwAKZSD
      LsHbKShgAFY7jHqIwkMm3N89kIqkQgrswwIBAg==
      -----END DH PARAMETERS-----
    hostnames:
      - id: "1"
        name: example001.com
        cc_token: "p70xAjo7b7lLMi-Y4tgixcE55POuVQh1dWqitJMyoxM"
        cc_payload: "p70xAjo7b7lLMi-Y4tgixcE55POuVQh1dWqitJMyoxM.hqI2tvoKxfy5mN1hvTLZwkt4o0WXwYv1uZFrvvr_sXM"
      - id: "2"
        name: example002.com
        # copied from tests/hostnames/hostname2.fullchain
        fullchain: |
          -----BEGIN CERTIFICATE-----
          MIIDtTCCAp2gAwIBAgIUTl0XanIE/nnHA5VasjBqL6QycnEwDQYJKoZIhvcNAQEL
          BQAwajELMAkGA1UEBhMCSUwxDzANBgNVBAgMBkNlbnRlcjERMA8GA1UEBwwIVGVs
          LUF2aXYxDTALBgNVBAoMBEFjbWUxDzANBgNVBAsMBkRldk9wczEXMBUGA1UEAwwO
          ZXhhbXBsZTAwMi5jb20wHhcNMjEwODI5MDgwNDM3WhcNMjIwODI5MDgwNDM3WjBq
          MQswCQYDVQQGEwJJTDEPMA0GA1UECAwGQ2VudGVyMREwDwYDVQQHDAhUZWwtQXZp
          djENMAsGA1UECgwEQWNtZTEPMA0GA1UECwwGRGV2T3BzMRcwFQYDVQQDDA5leGFt
          cGxlMDAyLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL3tID3M
          EYzbj9jce8RllwpdmG4eCxj1UyqJKLnabRCiZKzWR6stzYjHT+6jKgvdhmN49MGP
          QRk5+2xWS7e9WfRWwMWCbVbNEYdJBenVvVS3lM8FgARW+LVzlETEqXPHUztottIZ
          UPQCRFlmng7kvtCqDH2umUKifwO8bcVkMOXTHnItn5L+JGnYORR81I4uaCR7hbJe
          jv9soJW5xtZ7jBDJAGkvh3Kuhgu4y1AyzGvCgnnZiDKCk7UaO3BlRtOaZelH4eKg
          +VDPBZj2VXRz11Dwlm7SQyXQzO/V6a7mcfVa2VvOFKvDbt7/cJPNFXzTgkT6TCy3
          l9PvtAJFZ2Cwgs0CAwEAAaNTMFEwHQYDVR0OBBYEFHTi0uakDXc0OQtw7hdeh/Is
          R2ZIMB8GA1UdIwQYMBaAFHTi0uakDXc0OQtw7hdeh/IsR2ZIMA8GA1UdEwEB/wQF
          MAMBAf8wDQYJKoZIhvcNAQELBQADggEBACt/JQC57zgUUOgXSJWyQo3kNpqQ5m3g
          LhOamO0QOr+hJq70kN5LxbKDUzxBS7KcatMNCnDtzkV8kEMkbSDkoioHymu7/8FY
          YIACOUeZewumCjgaDraNqvqfIaoHaKJKFT8KQQJEyu6M1nlibwgZR8ZkSXJ3araQ
          HgE085qbAR+1puUj0WOSrFhPvDJ1+kUwJ0QAN62vinBzq99o+annG4fmivGQ9SN5
          hHZltfkoBD8SKjRUN8ZBkwtWLg5yDE6a1DGbV8KCD0juWgsD5dk3+SdFoxCmHKkP
          R+Bwwoz7s7dYjC/jUv9fFgrrGQCvgy4hvjP40BinFIcBl1FhpBChai0=
          -----END CERTIFICATE-----
        # copied from tests/hostnames/hostname2.privkey
        privkey: |
          -----BEGIN PRIVATE KEY-----
          MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC97SA9zBGM24/Y
          3HvEZZcKXZhuHgsY9VMqiSi52m0QomSs1kerLc2Ix0/uoyoL3YZjePTBj0EZOfts
          Vku3vVn0VsDFgm1WzRGHSQXp1b1Ut5TPBYAEVvi1c5RExKlzx1M7aLbSGVD0AkRZ
          Zp4O5L7Qqgx9rplCon8DvG3FZDDl0x5yLZ+S/iRp2DkUfNSOLmgke4WyXo7/bKCV
          ucbWe4wQyQBpL4dyroYLuMtQMsxrwoJ52YgygpO1GjtwZUbTmmXpR+HioPlQzwWY
          9lV0c9dQ8JZu0kMl0Mzv1emu5nH1WtlbzhSrw27e/3CTzRV804JE+kwst5fT77QC
          RWdgsILNAgMBAAECggEBAJ4sQdG1hlg88wu0dA8YXDXxxOTQeIWMqnqeSCCgXHyi
          Ah4/Rui0+JuVAmjH0liXYTiun4gj+h88Prv3EpAvTh9DsL/M46qKlrKIijg4HbnU
          OkY/WmJC3FahrzWmY0ldE2BC0R8gnl7ZFHswDypwLsoxFL4HDvSDyCwgXXsq+d4s
          B3jtAfVYtg18E6nYL1Bv81hTWogDulkmB7i1c0IDjcNpvh0V1QhqTVNnNj30gHjH
          F7o3ZbLMbSOilvcY7OSlFMTqOslB79qZ7ykCVBNTW2Z/VXKCdiIy1sFBXR1+YUtQ
          ZUrJEWCA1D6h/4dWwAMGXI7DDFlyP13OWMdK6g9JsIECgYEA9o0/rxUqTCvEnHXU
          Tqoof3aWQ7/69QSRQxs4rONcVhDWOuTOeF2zctg3Hz/e+0tP+mqEa2DwrLotO/2Y
          XLefqn5nR/5dcPe5S/1FtIZJRI8C8m955UDKUKxsQa9PdlWlHmDVFJtkMZlrX9ZM
          /4NugQzBU68XcgJKuTieHJHzISkCgYEAxTRc+ZRsK/bsVrSg8B15Xi5S4tkWiYDU
          pPv9hwgCTPMskYQPeWR+snpY5VF5GnDEZ3JEBXNIns35f+Gkw9jqrzaTOvYL1+mr
          xVbKehFPJTNifLiYnymho1yb2cvxHly0btmo9pAzw/tFw4MHakxwu42WyDcWz2J5
          jbNw/YAElQUCgYEAqnQa7DOoy4KS6ky4HC6d0wmsd2h52v1uZEOkmjqR8tqvEYZw
          jFzTnHmJGmyw/3Eg+RK9O/OIURJiBZCczrUQiPHc+7QK6/gIPlX65ATXELQCqJOT
          ZYC2nrGmIn9OY5RwlKEDj7yit3vG9ToWf6xhMI0d93ocrnCRMp7HCR+KRIkCgYEA
          q8l7nKagvIOzSay77a+fRF3SMm6t5UZm9vnU1sYxStsi3fhOio7yl4Ng4RLiDhhh
          30N44c6VWlFPoQjtQPY7Kjq+csRXeNTDn3qFk2R0r5FdoAwmV7AqcGaCFW5FMw/K
          1i2htHfVwEmpcjE4Sm8gXSFwUiU7J5k/DiNcsFfOpgkCgYB365bofv5RC5nSyE0a
          wOqPvl7V28S+N3KA7rPQ0f/YEIZGVkqADctVSww58RR4HhuvZB+AftkgYASjdp/I
          Usdvc/6xjTMKHazc7DZE1AW8SmN6+w1J0kE9ci6wH9NEutEF6XdDx0Hf3PxzzMeF
          rvQM7+qBc3yZCEmKu0ZtKu4GJA==
          -----END PRIVATE KEY-----
        cc_token: "x70xAjo7b7lLMi-Y4tgixcE55POuVQh1dWqitJMyoxM"
        cc_payload: "x70xAjo7b7lLMi-Y4tgixcE55POuVQh1dWqitJMyoxM.hqI2tvoKxfy5mN1hvTLZwkt4o0WXwYv1uZFrvvr_sXM"
      - id: "3"
        name: "example003.com"
        # copied from tests/hostnames/hostname3.chain
        chain: |
          -----BEGIN CERTIFICATE-----
          MIIDtTCCAp2gAwIBAgIUPyDv5nHsopcWmG7r8tEsRy6XTekwDQYJKoZIhvcNAQEL
          BQAwajELMAkGA1UEBhMCSUwxDzANBgNVBAgMBkNlbnRlcjERMA8GA1UEBwwIVGVs
          LUF2aXYxDTALBgNVBAoMBEFjbWUxDzANBgNVBAsMBkRldk9wczEXMBUGA1UEAwwO
          ZXhhbXBsZTAwMy5jb20wHhcNMjEwODI5MDgyNzAwWhcNMjIwODI5MDgyNzAwWjBq
          MQswCQYDVQQGEwJJTDEPMA0GA1UECAwGQ2VudGVyMREwDwYDVQQHDAhUZWwtQXZp
          djENMAsGA1UECgwEQWNtZTEPMA0GA1UECwwGRGV2T3BzMRcwFQYDVQQDDA5leGFt
          cGxlMDAzLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM3kCmdI
          HLwJz7DsigADqTEWCHG8dpjENjWqaL0S+SQ5li2YB7/CWfrR4IU6FofhAs3YC3F5
          odsZ+Odgq5lgza+iM+1Clf2asgAc9eaJp9PCHKgc+eap6BhouWF0dmODuyShJZ6j
          fe2DoR+0wHUmlsxClbr2vEvlskDvUDizZcGiloCng5ucV3iZbWTHiVEiJRsolp6s
          4Zg/Q1wBGq+YGXJUsSw9oaw4nxC3kjVldHQI6LslCzkAsz220BdYMVPMyJboHkx/
          cROfnU7RWGrZRlFtPq7zVaFJymPh1PjxaXOGwzOaxEWkb+WzRGiuRVC/BlXIrw17
          bYPlD0Jn3a+WZ30CAwEAAaNTMFEwHQYDVR0OBBYEFMGTHoACOjTHjBIPm+suwhIJ
          2By0MB8GA1UdIwQYMBaAFMGTHoACOjTHjBIPm+suwhIJ2By0MA8GA1UdEwEB/wQF
          MAMBAf8wDQYJKoZIhvcNAQELBQADggEBACEupCCxXkW5IHgSCA2RuHUhLRZxVUja
          Q9F0bozdrore4VQTieGk8idHw+8L/I+7QgBsI2/25O7bxJNkKyhY3GGyTG8kkYN9
          b4XNm6kCfoA5ey4M3+7/MTSTc3ApH0TxzE1IbDNGHAZs3ytgZ0PjxLdqvgS3rgIV
          hOcnD/6S1JfGO/QqSc9ssovB3ygZjuW72TXx5MRwLSk/ynQrmx6dqNtESQv3XSk3
          i49PMNJLzwG75hYP3tFikYDBWgiuBF0c62uNcxBmKgSJNJazmjsHGMS4PhE5A2uu
          y7f7EK5GX+hOAmzhxTWBlISaMW7DkmfTroQ6un9D/FPC7fEfCXnsMlU=
          -----END CERTIFICATE-----
        # copied from tests/hostnames/hostname3.fullchain
        fullchain: |
          -----BEGIN CERTIFICATE-----
          MIIDtTCCAp2gAwIBAgIUPyDv5nHsopcWmG7r8tEsRy6XTekwDQYJKoZIhvcNAQEL
          BQAwajELMAkGA1UEBhMCSUwxDzANBgNVBAgMBkNlbnRlcjERMA8GA1UEBwwIVGVs
          LUF2aXYxDTALBgNVBAoMBEFjbWUxDzANBgNVBAsMBkRldk9wczEXMBUGA1UEAwwO
          ZXhhbXBsZTAwMy5jb20wHhcNMjEwODI5MDgyNzAwWhcNMjIwODI5MDgyNzAwWjBq
          MQswCQYDVQQGEwJJTDEPMA0GA1UECAwGQ2VudGVyMREwDwYDVQQHDAhUZWwtQXZp
          djENMAsGA1UECgwEQWNtZTEPMA0GA1UECwwGRGV2T3BzMRcwFQYDVQQDDA5leGFt
          cGxlMDAzLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM3kCmdI
          HLwJz7DsigADqTEWCHG8dpjENjWqaL0S+SQ5li2YB7/CWfrR4IU6FofhAs3YC3F5
          odsZ+Odgq5lgza+iM+1Clf2asgAc9eaJp9PCHKgc+eap6BhouWF0dmODuyShJZ6j
          fe2DoR+0wHUmlsxClbr2vEvlskDvUDizZcGiloCng5ucV3iZbWTHiVEiJRsolp6s
          4Zg/Q1wBGq+YGXJUsSw9oaw4nxC3kjVldHQI6LslCzkAsz220BdYMVPMyJboHkx/
          cROfnU7RWGrZRlFtPq7zVaFJymPh1PjxaXOGwzOaxEWkb+WzRGiuRVC/BlXIrw17
          bYPlD0Jn3a+WZ30CAwEAAaNTMFEwHQYDVR0OBBYEFMGTHoACOjTHjBIPm+suwhIJ
          2By0MB8GA1UdIwQYMBaAFMGTHoACOjTHjBIPm+suwhIJ2By0MA8GA1UdEwEB/wQF
          MAMBAf8wDQYJKoZIhvcNAQELBQADggEBACEupCCxXkW5IHgSCA2RuHUhLRZxVUja
          Q9F0bozdrore4VQTieGk8idHw+8L/I+7QgBsI2/25O7bxJNkKyhY3GGyTG8kkYN9
          b4XNm6kCfoA5ey4M3+7/MTSTc3ApH0TxzE1IbDNGHAZs3ytgZ0PjxLdqvgS3rgIV
          hOcnD/6S1JfGO/QqSc9ssovB3ygZjuW72TXx5MRwLSk/ynQrmx6dqNtESQv3XSk3
          i49PMNJLzwG75hYP3tFikYDBWgiuBF0c62uNcxBmKgSJNJazmjsHGMS4PhE5A2uu
          y7f7EK5GX+hOAmzhxTWBlISaMW7DkmfTroQ6un9D/FPC7fEfCXnsMlU=
          -----END CERTIFICATE-----
        # copied from tests/hostnames/hostname3.privkey
        privkey: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDN5ApnSBy8Cc+w
          7IoAA6kxFghxvHaYxDY1qmi9EvkkOZYtmAe/wln60eCFOhaH4QLN2AtxeaHbGfjn
          YKuZYM2vojPtQpX9mrIAHPXmiafTwhyoHPnmqegYaLlhdHZjg7skoSWeo33tg6Ef
          tMB1JpbMQpW69rxL5bJA71A4s2XBopaAp4ObnFd4mW1kx4lRIiUbKJaerOGYP0Nc
          ARqvmBlyVLEsPaGsOJ8Qt5I1ZXR0COi7JQs5ALM9ttAXWDFTzMiW6B5Mf3ETn51O
          0Vhq2UZRbT6u81WhScpj4dT48WlzhsMzmsRFpG/ls0RorkVQvwZVyK8Ne22D5Q9C
          Z92vlmd9AgMBAAECggEBAJJNDZtwYYK4kg2NN05lS49msZ9oJPnOyxp9OanI1qKI
          DQ/e7Pq09s1E336r1SC+ogh1EUSUApA3N2fqiGUXpXC9GJrqarxndT6hVZZ4kHnn
          gAdxd54Rc6wMllYKtKloDM4teBbu4+enVhG6ldtpDVSdp9nPw+NGl9COfPmdeJwL
          Tskp5vH3kMwwN28f8YJvXoMFxvomauc2vJfTEAELaH78Z3CivEsO/50yyN5i5Q+e
          +BwErYVkPBuEdGYUeyEhH5w11BsLMg3MIKS/uqK23c5MmRv2fdc6QAOsYUvbIQoO
          7M8AacpUmfVnV6oIQFKFzB7+Yx70R9xeoL3sTGUvM/0CgYEA713/MeLdK/Uhuy3l
          03K7vizhsUtEKS2OxQHl3GjHX7T9FTVK8lqQ7CCmEe5j5auiAZivD+ly2eBR1beg
          tlp01EEFF/sBj8HDl+vy2k5SSOOpEqCyYHPKB++Ewur0qJGgo52E4pkDU/FcYGQ7
          ij8gqB0CyPvCpbCSJEo9vSLtQucCgYEA3DKL0i/YwV0UlVdS/l6XH8zTJA97toWx
          mX0ZHeW82Dmbf1+WKsKZbhQZtqvhoJ+7vjD/JpyqORVxmaAZztd6tCuM4atIGa7L
          YOeTT3+B6cUSJ0UfqYKS0pbcp9jZTtYJPu/z6lV4AUEiSCy10+2xkmFqq/Y0vQZ+
          rNNniOrA2fsCgYBLTh0dCqxeSe5kvtnRHgVmnSQb7PvyoHyMCj7Qir4+o+gDJhMA
          D/IL93GHrqIK/WYobmqU7PLPDL1yKSUMeYTLyfDaTIN/QIxSXU6303AbslPcomW7
          5nGm8XmpANYbukT5dHL7/vuHCyXuxVnd8mJJwWbA6EOicNxpQloOCNDv/QKBgAGP
          9kACiOYuU+QPX45ge3AFUwYxee48mpr9MT1uEN3z4q+PrRAWm2IVkG0kYRBzsbBS
          xqyudeK7zTeK1EQMcVlv6ar8PSG5hMXmPrxUqkZPWKagre3U+Fe4LE6gkkIl8KDa
          sP9bpeNUY/rhHlUnnZftSwV3VL52mlV9loF5MO8bAoGANYsFcsRJuLS9fXlz4K34
          TlNp1nUTi8p6IRvzeOMsb07iAHofLCm1hnGgv/aTS5IoutC5it4+L1caI85juPsn
          5enKvGEmJL8YPNIwTboLWe90uXRIEkdBhOOTCwFoD5XY6BpBjLXhdi+px016e/n5
          sZocBZEI2yaD4+scgCoG0uA=
          -----END PRIVATE KEY-----
        cc_token: ""
        cc_payload: ""
    DISABLE_HTTP: false
    DISABLE_HTTPS: false
    CDN_CACHE_ENABLE: false
    CDN_CACHE_PROXY_PATH: "/var/cache/nginx/minio/cache"
    CDN_CACHE_PROXY_KEYS_MAX_SIZE: "10m"
    CDN_CACHE_PROXY_MAX_SIZE: "1g"
    CDN_CACHE_PROXY_INACTIVE: "1m"
    CDN_CACHE_PROXY_TEMP_PATH: "/var/cache/nginx/minio/temp"
    CDN_CACHE_PROXY_BUFFERS: "8 16k"
    CDN_CACHE_PROXY_BUFFER_SIZE: "16k"
    CDN_CACHE_PROXY_BUSY_BUFFERS_SIZE: "32k"
    CDN_CACHE_PROXY_CACHE_VALID_200: "1m"
    CDN_CACHE_NOCACHE_REGEX: '\.(pdf|txt|json)$'
    # dedicated cache volume configuration for nginx cache
    # if not specified - uses the minio cache at minio.volumes.cache
    cacheVolume: ""
    cacheVolumeSubPath: "_cdncache_"
    cacheVolumeMountPath: "/var/cache/nginx/minio"

    # External: https://github.com/cloudwebmanage/cwm-keda-external-scaler
    # CPU: https://keda.sh/docs/2.3/scalers/cpu/
    # Memory: https://keda.sh/docs/2.3/scalers/memory/
    scaledobject:
      enabled: false
      type: external          # external, cpu, memory
      # external
      pollingInterval: 10
      cooldownPeriod:  60
      minReplicaCount: 1
      maxReplicaCount: 10
      # advanced:
      #   restoreToOriginalReplicaCount: true
      #   horizontalPodAutoscalerConfig:
      #     behavior:
      #       scaleDown:
      #         stabilizationWindowSeconds: 30
      #         policies:
      #         - type: Percent
      #           value: 80
      #           periodSeconds: 15
      isActiveTtlSeconds: "60"
      scalePeriodSeconds: "60"
      scaleMetricName: "num_requests_misc"
      targetValue: "10"
      # cpu / memory
      metricType: Utilization # Utilization, Value, AverageValue
      metricValue: "80"

# each object have required attributes: apiVersion, kind, name, spec
extraObjects: []
