name: CI-client
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  ci-client:
    runs-on: ubuntu-20.04
    steps:
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s https://raw.githubusercontent.com/CloudWebManage/uumpa-ci-toolbox/main/bin/github_actions_install.sh \
          | bash -s 807a483b65f3ec28787300499d961338a9d6bc4a CloudWebManage/uumpa-ci-toolbox &&\
        uci github actions self-checkout --config-user-name "cwm-worker-deployment-minio-ci" &&\
        uci github actions docker-login &&\
        uci docker build-cache \
          --cache-from ghcr.io/cloudwebmanage/cwm-worker-deployment-minio/client:latest \
          -- -t client client &&\
        uci docker tag-push \
          --source-tag-name client \
          --push-tag-name ghcr.io/cloudwebmanage/cwm-worker-deployment-minio/client:$GITHUB_SHA &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          uci docker tag-push \
            --source-tag-name client \
            --push-tag-name ghcr.io/cloudwebmanage/cwm-worker-deployment-minio/client:latest
        fi
